# Version
version: '{build}'

# Branches
#branches:
#  only: master

skip_tags: true

# Build Server Image
image: Visual Studio 2017 Preview

# Install Script
install:
  - cmd: dotnet --version

# Build Script
build_script:
  - ps: . .\build.ps1 -Verbosity Diagnostic

# Tests
test: false

# Define artifacts
artifacts:
  - path: 'build\*.nupkg'