// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("FuManchu")]
[assembly: AssemblyProductAttribute("FuManchu")]
[assembly: AssemblyCopyrightAttribute("Copyright © FuManchu Project 2015")]
[assembly: AssemblyVersionAttribute("1.3.0.0")]
[assembly: AssemblyFileVersionAttribute("1.3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.3.0.0";
    }
}
